# Generated by Django 3.2.6 on 2021-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=2000)),
                ('linkedin', models.CharField(max_length=100)),
                ('objective', models.TextField(max_length=2000)),
                ('ssc', models.FloatField()),
                ('ssc_univ', models.CharField(max_length=100)),
                ('hsc', models.FloatField()),
                ('hsc_univ', models.CharField(max_length=100)),
                ('grad', models.FloatField()),
                ('grad_univ', models.CharField(max_length=100)),
                ('postgrad', models.FloatField()),
                ('postgrad_univ', models.CharField(max_length=100)),
                ('exp', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
                ('projects', models.TextField(max_length=2000)),
            ],
        ),
    ]
