# Generated by Django 3.2.6 on 2021-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gradp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad',
            field=models.CharField(max_length=100),
        ),
    ]
