# Generated by Django 3.2.6 on 2021-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeForm', '0002_auto_20210905_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_univ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postgrad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postgrad_univ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
